/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitnessapp;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author presl
 */
public class FitnessGUI extends javax.swing.JFrame {
    //vars
    //array
    private ArrayList <Fitness> FitnessArray = new ArrayList<Fitness>();
    private String day, time, classType, trainerName;
    private int duration, numOfReps,count;
    private double caloriesBurned;
    File f;
    FileInputStream fStream;
    ObjectInputStream oStream;
    /**
     * Creates new form FitnessGUI
     */
    public FitnessGUI() {
        initComponents();
        //initialising variables
        day = "";
        time = "";
        duration =0;
        numOfReps = 0;
        classType = "";
        trainerName = "";
        caloriesBurned = 0.0;
        count = 0;
        
    
  //makes the dat file load up upon running the program

    try {
        f = new File("fitness.dat");
        fStream = new FileInputStream(f);
        oStream = new ObjectInputStream(fStream);
        

        FitnessArray = (ArrayList<Fitness>) oStream.readObject();
        oStream.close();
    } catch (IOException | ClassNotFoundException e) {
        System.out.println(e);
    }
    for (Fitness x : FitnessArray) {
        JOptionPane.showMessageDialog(null, "  Saved Records \n \n "+x.showDetails());
    }

        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnActivityGroup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        caloriesBurnedLabel = new javax.swing.JLabel();
        repsLabel = new javax.swing.JLabel();
        cTypeLabel = new javax.swing.JLabel();
        tNameLabel = new javax.swing.JLabel();
        dayTF = new javax.swing.JTextField();
        timeTF = new javax.swing.JTextField();
        durationTF = new javax.swing.JTextField();
        caloriesBurnedTF = new javax.swing.JTextField();
        numOfRepsTF = new javax.swing.JTextField();
        classTypeTF = new javax.swing.JTextField();
        trainerTF = new javax.swing.JTextField();
        gymRB = new javax.swing.JRadioButton();
        fitnessRB = new javax.swing.JRadioButton();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        delLastBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("Fitness App");

        dayLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        dayLabel.setText("Day");

        timeLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        timeLabel.setText("Time");

        durationLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        durationLabel.setText("Duration");

        caloriesBurnedLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        caloriesBurnedLabel.setText("Calories Burned");

        repsLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        repsLabel.setText("Number Of Reps");

        cTypeLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cTypeLabel.setText("Class Type");

        tNameLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        tNameLabel.setText("Trainer Name");

        dayTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTFActionPerformed(evt);
            }
        });

        caloriesBurnedTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caloriesBurnedTFActionPerformed(evt);
            }
        });

        btnActivityGroup.add(gymRB);
        gymRB.setText("Gym Workout");
        gymRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gymRBActionPerformed(evt);
            }
        });

        btnActivityGroup.add(fitnessRB);
        fitnessRB.setText("Fitness Classes");
        fitnessRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fitnessRBActionPerformed(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        delLastBtn.setText("Delete Last Activity Added");
        delLastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delLastBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(displayBtn)
                        .addGap(29, 29, 29)
                        .addComponent(saveBtn)
                        .addGap(28, 28, 28)
                        .addComponent(delLastBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(caloriesBurnedLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(caloriesBurnedTF, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(timeLabel)
                                    .addComponent(durationLabel))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dayTF)
                                    .addComponent(timeTF)
                                    .addComponent(durationTF, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(repsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numOfRepsTF))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tNameLabel)
                                        .addComponent(cTypeLabel)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(classTypeTF)
                                    .addComponent(trainerTF))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gymRB)
                            .addComponent(fitnessRB))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dayLabel)
                            .addComponent(dayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeLabel)
                            .addComponent(timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(durationLabel)
                            .addComponent(durationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caloriesBurnedLabel)
                            .addComponent(caloriesBurnedTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(repsLabel)
                            .addComponent(numOfRepsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cTypeLabel)
                            .addComponent(classTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNameLabel)
                            .addComponent(trainerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(gymRB)
                        .addGap(18, 18, 18)
                        .addComponent(fitnessRB)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(displayBtn)
                    .addComponent(saveBtn)
                    .addComponent(delLastBtn))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dayTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTFActionPerformed

    private void fitnessRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fitnessRBActionPerformed
        // TODO add your handling code here:
        //sets visible and invisible certain text fields and labels when fitness classes radio button is selected
         repsLabel.setVisible(false);
        numOfRepsTF.setVisible(false);
        cTypeLabel.setVisible(true);
        classTypeTF.setVisible(true);
        tNameLabel.setVisible(true);
        trainerTF.setVisible(true);
       
    }//GEN-LAST:event_fitnessRBActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        for(Fitness x:FitnessArray){
            //displays the show details that is overidden in instansiable classes
            JOptionPane.showMessageDialog(null,x.showDetails());
        }
        //give error message when array is empty
         if(FitnessArray.isEmpty()){
            JOptionPane.showMessageDialog(null,"Sorry there are no fitness activities to display");
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void gymRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gymRBActionPerformed
        // TODO add your handling code here:
        //sets visible and invisible certain text fields and labels when gym workout radio button is selected
         cTypeLabel.setVisible(false);
        classTypeTF.setVisible(false);
        tNameLabel.setVisible(false);
        trainerTF.setVisible(false);
        repsLabel.setVisible(true);
        numOfRepsTF.setVisible(true);
    }//GEN-LAST:event_gymRBActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
         if(gymRB.isSelected()){
            GymWorkout g = new GymWorkout();
            //essentially links the variables to the text fields, parsing the integers and doubles
            day = dayTF.getText();
            time = timeTF.getText();
            duration = Integer.parseInt(durationTF.getText());
            caloriesBurned = Double.parseDouble(caloriesBurnedTF.getText());
            numOfReps = Integer.parseInt(numOfRepsTF.getText());
            
            g.setDay(day);
            g.setTime(time);
            g.setDuration(duration);
            g.setCaloriesBurned(caloriesBurned);
            g.setNumOfReps(numOfReps);
            //adds to array
            FitnessArray.add(g);
            
            //success message that gym workout has been added
            JOptionPane.showMessageDialog(null,"Gym Workout Activity added successfully");
        }
        else if(fitnessRB.isSelected()){
            FitnessClasses fc = new FitnessClasses();
            day = dayTF.getText();
            time = timeTF.getText();
            duration = Integer.parseInt(durationTF.getText());
            caloriesBurned = Double.parseDouble(caloriesBurnedTF.getText());
            classType = classTypeTF.getText();
            trainerName = trainerTF.getText();
            fc.setDay(day);
            fc.setTime(time);
            fc.setDuration(duration);
            fc.setCaloriesBurned(caloriesBurned);
            fc.setClassType(classType);
            fc.setTrainerName(trainerName);
            //adds to array
            FitnessArray.add(fc);
            //success message that it has been added
            JOptionPane.showMessageDialog(null,"Fitness class activity added successfully");
        }
         
         
    }//GEN-LAST:event_addBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        //saving the file
         try{
            
            FileOutputStream fStream = new FileOutputStream(f);
            ObjectOutputStream oStream = new ObjectOutputStream(fStream);
            oStream.writeObject(FitnessArray);
            oStream.close();
             
        }
        catch(IOException e){
            System.out.println(e);
        }
         //success message that the file has been saved
       JOptionPane.showMessageDialog(null, "File saved succesfully");
      
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void delLastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delLastBtnActionPerformed
        // TODO add your handling code here:
        if (FitnessArray.isEmpty()) {
         JOptionPane.showMessageDialog(null, "sorry there are no fitness activities to delete");
    } else {
            //deletes the last added activity
       FitnessArray.remove(FitnessArray.size() - 1);
       JOptionPane.showMessageDialog(null, "Activity successfully deleted");
    }
        //automatically saves the file when the delete button is pressed
        try{
            
            FileOutputStream fStream = new FileOutputStream(f);
            ObjectOutputStream oStream = new ObjectOutputStream(fStream);
            oStream.writeObject(FitnessArray);
            oStream.close();
             
        }
        catch(IOException e){
            System.out.println(e);
        }
        JOptionPane.showMessageDialog(null, "The file has been saved successfully");
        
      
    }//GEN-LAST:event_delLastBtnActionPerformed

    private void caloriesBurnedTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caloriesBurnedTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caloriesBurnedTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FitnessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FitnessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FitnessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FitnessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FitnessGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.ButtonGroup btnActivityGroup;
    private javax.swing.JLabel cTypeLabel;
    private javax.swing.JLabel caloriesBurnedLabel;
    private javax.swing.JTextField caloriesBurnedTF;
    private javax.swing.JTextField classTypeTF;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JTextField dayTF;
    private javax.swing.JButton delLastBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JTextField durationTF;
    private javax.swing.JRadioButton fitnessRB;
    private javax.swing.JRadioButton gymRB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField numOfRepsTF;
    private javax.swing.JLabel repsLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel tNameLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JTextField timeTF;
    private javax.swing.JTextField trainerTF;
    // End of variables declaration//GEN-END:variables
}
